ProxySuite:
  SQL:
  - 'localhost'
  - '3306'
  - 'Database'
  - 'Username'
  - 'Password'
  TablePrefix: ''
  ModulesEnabled:
    Teleport: true
    Warp: true
    Home: true
    BanKickWarn: true
    Note: true
    Portal: true
    Spawn: true
    Vanish: true
    Fly: true
    Gamemode: true
  Messages:
    MOTD:
    - Welcome to the server
    - Checkout the website
    - Be nice to each other
    TimeFormat: dd.MM.yyyy HH:mm:ss
    JoinMessageDelayMS: 150
  Server:
    SwitchCheckDelayMS: 500
  Teleport:
    Timeout: 180
    DefaultCooldown: 10
  Homes:
    DefaultMaximum: 10
    DefaultMaximumPerWorld: 5
    SortAlphabetically: false
  Warnings:
    TimeUntilArchive: 120
    KickOnWarn: true
    UntilBan: 2
  Security:
    IPJoinInfo: -1
    MaxPlayersWithSameIP: -1
  Logging:
    CommandOutputEnabled: true
    LastMessagesLogged: 5
  Announcements:
    Interval: 300
    Prefix: '&4[Announcement]&r '
    PrefixJson: '{"text":"[Announcement] ","color":"red"}'
    Random: false
  WelcomeSound:
    Enabled: false
    Sound: 'ENTITY_VILLAGER_YES' # See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    Volume: 10
    Pitch: 1